package com.spring.rest.v2.model;

import org.hibernate.validator.constraints.NotBlank;
import org.springframework.web.multipart.MultipartFile;

import com.spring.rest.v2.setting.ValidSetting;

public class User {
    
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.img
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.account
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	@NotBlank(message = "{}")
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	@NotBlank(message = "{}")
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.img
	 * @return  the value of user.img
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.img
	 * @param img  the value for user.img
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.account
	 * @return  the value of user.account
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.account
	 * @param account  the value for user.account
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Jul 11 14:26:01 AWST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
	/*
	 * 自定義欄位
	 */

	@ValidSetting
    private MultipartFile file;

	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}
}